model_list:
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: ollama/gpt-oss:20b
    litellm_params:
      model: ollama/gpt-oss:20b
      api_base: "http://host.docker.internal:11434"
